name = "ThesisTools"
uuid = "26dcc786-85df-5edc-b560-6076d5dbac63"
author = "Fredrik Bagge Carlson <baggepinnen@gmail.com>"
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"
